#!/bin/bash
# Runs the N-validator network generated by generate-network.mjs as plain
# native `besu` processes (like the repo's existing network/start-nodes.sh)
# instead of Docker containers. Fault injection on this network uses
# node-ctl.sh (SIGKILL / relaunch one validator) in place of docker stop/start.
#
# Usage: ./start-native.sh <nodeCount> [--light]
#
# Memory containment: each validator runs as its own transient systemd --user
# service (p4p-besu-n<N>-v<i>.service, launched by node-ctl.sh) inside
# p4p-perf.slice, NOT as a child of the invoking shell. Previous runs launched
# besu from the VS Code terminal, so the JVMs lived in VS Code's snap cgroup
# scope; on this no-swap 7.7G box the kernel OOM killer fired (journal: "Out of
# memory: Killed process (java)") and systemd then tore down the whole
# snap.code scope, crashing VS Code. Now each node has a hard MemoryMax - an
# overrun kills only that node (systemd records Result=oom-kill, which the
# watchdog reports) - and the slice has a total cap.
#
# Tunables (env): P4P_NODE_MEM_MB  cgroup MemoryMax per validator
#                 P4P_NODE_HEAP_MB JVM -Xmx per validator
#                 P4P_SLICE_MEM_MB MemoryMax for the whole p4p-perf.slice
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

N="${1:?Usage: ./start-native.sh <nodeCount> [--light]}"
LIGHT="${2:-}"
HEAP_MB="${P4P_NODE_HEAP_MB:-2048}"
NODE_MEM_MB="${P4P_NODE_MEM_MB:-2900}"
if [ "$LIGHT" = "--light" ]; then
    HEAP_MB="${P4P_NODE_HEAP_MB:-512}"
    NODE_MEM_MB="${P4P_NODE_MEM_MB:-1100}"
fi
SLICE="p4p-perf.slice"
UNIT_PREFIX="p4p-besu-n${N}-v"

# refuse to start on top of a still-running network of the same size
if systemctl --user list-units --plain --no-legend "${UNIT_PREFIX}*" 2>/dev/null | grep -q .; then
    echo "Units ${UNIT_PREFIX}* already exist - run stop-native.sh ${N} first" >&2
    exit 1
fi

GEN_DIR="generated/n${N}"
CONFIG_DIR="${GEN_DIR}/config"
if [ ! -f "${CONFIG_DIR}/genesis.json" ]; then
    echo "No generated config at ${CONFIG_DIR} - run: node generate-network.mjs ${N} [--light]" >&2
    exit 1
fi

DATA_ROOT="${GEN_DIR}/data-native"
rm -rf "$DATA_ROOT"
mkdir -p "$DATA_ROOT"
for ((i = 1; i <= N; i++)); do : > "${GEN_DIR}/validator${i}.log"; done

mapfile -t ADDRS < <(find "${CONFIG_DIR}/keys" -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort)
if [ "${#ADDRS[@]}" -ne "$N" ]; then
    echo "Expected ${N} validator keys under ${CONFIG_DIR}/keys, found ${#ADDRS[@]}" >&2
    exit 1
fi

RPC_BASE=$((20000 + N * 100))

printf 'HEAP_MB=%s\nNODE_MEM_MB=%s\n' "$HEAP_MB" "$NODE_MEM_MB" > "${GEN_DIR}/node-env"

PID_FILE="${GEN_DIR}/native-pids.txt"
: > "$PID_FILE"

echo "Starting ${N} native besu validators (RPC ports ${RPC_BASE}..$((RPC_BASE + N - 1))) as systemd units ${UNIT_PREFIX}1..${N}, heap ${HEAP_MB}M, MemoryMax ${NODE_MEM_MB}M each..."
for ((i = 1; i <= N; i++)); do
    bash node-ctl.sh "$N" "$i" start
    if [ "$i" -eq 1 ]; then
        if [ -n "${P4P_SLICE_MEM_MB:-}" ]; then
            systemctl --user set-property --runtime "$SLICE" MemoryMax="${P4P_SLICE_MEM_MB}M"
        fi
        sleep 3   # give the bootnode a head start
    fi
    systemctl --user show -p MainPID --value "${UNIT_PREFIX}${i}" >> "$PID_FILE"
done

# Overwrites network-meta.json (same filename generate-network.mjs uses) with
# native RPC endpoints instead of docker container info, so
# deploy-and-configure.js and the fault-injection scripts work unmodified.
# "backend": "native" tells fault-injection/lib.sh to use node-ctl.sh instead
# of docker stop/start; regenerate with generate-network.mjs for Docker.
{
    echo '{'
    echo '  "nodeCount": '"$N"','
    echo '  "backend": "native",'
    echo '  "validators": ['
    for ((i = 0; i < N; i++)); do
        comma=","
        if [ "$i" -eq $((N - 1)) ]; then comma=""; fi
        echo '    { "address": "'"${ADDRS[$i]}"'", "rpcUrl": "http://127.0.0.1:'"$((RPC_BASE + i))"'", "unit": "'"${UNIT_PREFIX}$((i + 1))"'" }'"$comma"
    done
    echo '  ],'
    echo '  "adminKeyPath": "perf-testing/network/'"${CONFIG_DIR}"'/keys/'"${ADDRS[0]}"'/key",'
    echo '  "maxTolerableFaults": '$(( (N - 1) / 3 ))
    echo '}'
} > "${GEN_DIR}/network-meta.json"

echo "PIDs written to ${PID_FILE}. Waiting for RPC to come up..."
sleep 5
for ((i = 0; i < N; i++)); do
    port=$((RPC_BASE + i))
    curl -s -m 3 -X POST -H 'Content-Type: application/json' \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
        "http://127.0.0.1:${port}" >/dev/null && echo "  validator$((i+1)) (port $port): up" || echo "  validator$((i+1)) (port $port): NOT RESPONDING YET"
done
echo "network-meta written to ${GEN_DIR}/network-meta.json"
